### **Synthetic microdata from sf1 using database reconstruction**
HHGQ (3) $*$ VOTINGAGE (2) $*$ HISPANIC (2) $*$ RACE (63) $*$ SEX (2) [from sf1 constraints]  
---------------->         
HHGQ (8) $*$ VOTINGAGE (2) $*$ HISPANIC (2) $*$ CENRACE (63)

Prepare query constraints from sf1 (*cons*) 

*   P5: HISPANIC OR LATINO ORIGIN BY RACE
*   P8: RACE
*   P9: HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE
*   P12A-G: SEX BY AGE BY RACE
*   P43: GROUP QUARTERS POPULATION BY SEX BY AGE BY GROUP QUARTERS TYPE

In [73]:
# %cd "/content/gdrive/My Drive/Colab Notebooks/census_privacy"
import pandas as pd
import string

## P1: TOTAL POPULATION
filename_p1 = 'franklin/sf1/franklin_P1.csv'
data_p1 = pd.read_csv(filename_p1)
data_p1 = data_p1.drop(columns=["FILEID", "STUSAB", "SUMLEV", "LOGRECNO", "REGION", "DIVISION", "STATE", "COUNTY",
                                "TRACT", "BLOCK", "GEOID10"])

## P5: HISPANIC OR LATINO ORIGIN BY RACE
filename_p5 = 'franklin/sf1/franklin_P5.csv'
data_p5 = pd.read_csv(filename_p5)
data_p5 = data_p5.drop(columns=["FILEID", "STUSAB", "SUMLEV", "LOGRECNO", "REGION", "DIVISION", "STATE", "COUNTY",
                                "TRACT", "BLOCK", "P0050001", "P0050002", "P0050010"])

## P8: RACE
filename_p8 = 'franklin/sf1/franklin_P8.csv'
data_p8 = pd.read_csv(filename_p8)
data_p8 = data_p8.drop(columns=["FILEID", "STUSAB", "SUMLEV", "LOGRECNO", "REGION", "DIVISION", "STATE", "COUNTY",
                                "TRACT", "BLOCK", "P0080001", "P0080002", "P0080009", "P0080010", "P0080026", 
                                "P0080047", "P0080063", "P0080070"])

## P9: HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE
filename_p9 = 'franklin/sf1/franklin_P9.csv'
data_p9 = pd.read_csv(filename_p9)
data_p9 = data_p9.drop(columns=["FILEID", "STUSAB", "SUMLEV", "LOGRECNO", "REGION", "DIVISION", "STATE", "COUNTY",
                                "TRACT", "BLOCK", "P0090001", "P0090002", "P0090003", "P0090004", "P0090011", 
                                "P0090012", "P0090028", "P0090049", "P0090065", "P0090072"])

## P12A: SEX BY AGE (WHITE ALONE)
filename_p12A = 'franklin/sf1/franklin_P12A.csv'
data_p12A = pd.read_csv(filename_p12A)
data_p12A["P012A00A"] = sum([data_p12A["P012A0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12A["P012A00B"] = sum([data_p12A["P012A0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12A["P012A00C"] = sum([data_p12A["P012A0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12A["P012A00D"] = sum([data_p12A["P012A0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12A = data_p12A[["P012A00A", "P012A00B", "P012A00C", "P012A00D"]]

## P12B: SEX BY AGE (BLACK OR AFRICAN AMERICAN ALONE)
filename_p12B = 'franklin/sf1/franklin_P12B.csv'
data_p12B = pd.read_csv(filename_p12B)
data_p12B["P012B00A"] = sum([data_p12B["P012B0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12B["P012B00B"] = sum([data_p12B["P012B0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12B["P012B00C"] = sum([data_p12B["P012B0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12B["P012B00D"] = sum([data_p12B["P012B0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12B = data_p12B[["P012B00A", "P012B00B", "P012B00C", "P012B00D"]]

## P12C: SEX BY AGE (AMERICAN INDIAN AND ALASKA NATIVE ALONE)
filename_p12C = 'franklin/sf1/franklin_P12C.csv'
data_p12C = pd.read_csv(filename_p12C)
data_p12C["P012C00A"] = sum([data_p12C["P012C0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12C["P012C00B"] = sum([data_p12C["P012C0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12C["P012C00C"] = sum([data_p12C["P012C0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12C["P012C00D"] = sum([data_p12C["P012C0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12C = data_p12C[["P012C00A", "P012C00B", "P012C00C", "P012C00D"]]

## P12D: SEX BY AGE (ASIAN ALONE)
filename_p12D = 'franklin/sf1/franklin_P12D.csv'
data_p12D = pd.read_csv(filename_p12D)
data_p12D["P012D00A"] = sum([data_p12D["P012D0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12D["P012D00B"] = sum([data_p12D["P012D0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12D["P012D00C"] = sum([data_p12D["P012D0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12D["P012D00D"] = sum([data_p12D["P012D0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12D = data_p12D[["P012D00A", "P012D00B", "P012D00C", "P012D00D"]]

## P12E: SEX BY AGE (NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE)
filename_p12E = 'franklin/sf1/franklin_P12E.csv'
data_p12E = pd.read_csv(filename_p12E)
data_p12E["P012E00A"] = sum([data_p12E["P012E0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12E["P012E00B"] = sum([data_p12E["P012E0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12E["P012E00C"] = sum([data_p12E["P012E0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12E["P012E00D"] = sum([data_p12E["P012E0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12E = data_p12E[["P012E00A", "P012E00B", "P012E00C", "P012E00D"]]

## P12F: SEX BY AGE (SOME OTHER RACE ALONE)
filename_p12F = 'franklin/sf1/franklin_P12F.csv'
data_p12F = pd.read_csv(filename_p12F)
data_p12F["P012F00A"] = sum([data_p12F["P012F0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12F["P012F00B"] = sum([data_p12F["P012F0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12F["P012F00C"] = sum([data_p12F["P012F0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12F["P012F00D"] = sum([data_p12F["P012F0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12F = data_p12F[["GEOID10", "P012F00A", "P012F00B", "P012F00C", "P012F00D"]]

## P12G: SEX BY AGE (TWO OR MORE RACES)
filename_p12G = 'franklin/sf1/franklin_P12G.csv'
data_p12G = pd.read_csv(filename_p12G)
data_p12G["P012G00A"] = sum([data_p12G["P012G0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(3, 7)])
data_p12G["P012G00B"] = sum([data_p12G["P012G0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(7, 26)])
data_p12G["P012G00C"] = sum([data_p12G["P012G0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(27, 31)])
data_p12G["P012G00D"] = sum([data_p12G["P012G0%s" % '{number:0{width}d}'.format(width=2, number=i)] 
                             for i in range(31, 50)])
data_p12G = data_p12G[["P012G00A", "P012G00B", "P012G00C", "P012G00D"]]

## P43: GROUP QUARTERS POPULATION BY SEX BY AGE BY GROUP QUARTERS TYPE
filename_p43 = 'franklin/sf1/franklin_P43.csv'
data_p43 = pd.read_csv(filename_p43)
data_p43["P043A001"] = data_p12A["P012A00A"] + data_p12B["P012B00A"] + data_p12C["P012C00A"]+ data_p12D["P012D00A"] + data_p12E["P012E00A"] + data_p12F["P012F00A"] + data_p12G["P012G00A"] - data_p43["P0430003"]
data_p43["P043A002"], data_p43["P043A003"], data_p43["P043A004"], data_p43["P043A005"] = data_p43[["P0430005"]], data_p43[["P0430006"]], data_p43[["P0430007"]], data_p43[["P0430008"]]
data_p43["P043A006"], data_p43["P043A007"], data_p43["P043A008"] = data_p43[["P0430010"]], data_p43[["P0430011"]], data_p43[["P0430012"]]
data_p43["P043A009"] = data_p12A["P012A00B"] + data_p12B["P012B00B"] + data_p12C["P012C00B"]+ data_p12D["P012D00B"] + data_p12E["P012E00B"] + data_p12F["P012F00B"] + data_p12G["P012G00B"] - data_p43["P0430013"] - data_p43["P0430023"]
data_p43["P043A010"] = sum([data_p43["P0430015"], data_p43["P0430025"]])
data_p43["P043A011"] = sum([data_p43["P0430016"], data_p43["P0430026"]])
data_p43["P043A012"] = sum([data_p43["P0430017"], data_p43["P0430027"]])
data_p43["P043A013"] = sum([data_p43["P0430018"], data_p43["P0430028"]])
data_p43["P043A014"] = sum([data_p43["P0430020"], data_p43["P0430030"]])
data_p43["P043A015"] = sum([data_p43["P0430021"], data_p43["P0430031"]])
data_p43["P043A016"] = sum([data_p43["P0430022"], data_p43["P0430032"]])
data_p43["P043A017"] = data_p12A["P012A00C"] + data_p12B["P012B00C"] + data_p12C["P012C00C"]+ data_p12D["P012D00C"] + data_p12E["P012E00C"] + data_p12F["P012F00C"] + data_p12G["P012G00C"] - data_p43["P0430034"]
data_p43["P043A018"], data_p43["P043A019"], data_p43["P043A020"], data_p43["P043A021"] = data_p43[["P0430036"]], data_p43[["P0430037"]], data_p43[["P0430038"]], data_p43[["P0430039"]]
data_p43["P043A022"], data_p43["P043A023"], data_p43["P043A024"] = data_p43[["P0430041"]], data_p43[["P0430042"]], data_p43[["P0430043"]]
data_p43["P043A025"] = data_p12A["P012A00D"] + data_p12B["P012B00D"] + data_p12C["P012C00D"]+ data_p12D["P012D00D"] + data_p12E["P012E00D"] + data_p12F["P012F00D"] + data_p12G["P012G00D"] - data_p43["P0430044"] - data_p43["P0430054"]
data_p43["P043A026"] = sum([data_p43["P0430046"], data_p43["P0430056"]])
data_p43["P043A027"] = sum([data_p43["P0430047"], data_p43["P0430057"]])
data_p43["P043A028"] = sum([data_p43["P0430048"], data_p43["P0430058"]])
data_p43["P043A029"] = sum([data_p43["P0430049"], data_p43["P0430059"]])
data_p43["P043A030"] = sum([data_p43["P0430051"], data_p43["P0430061"]])
data_p43["P043A031"] = sum([data_p43["P0430052"], data_p43["P0430062"]])
data_p43["P043A032"] = sum([data_p43["P0430053"], data_p43["P0430063"]])
data_p43 = data_p43[["P043A0%s" % '{number:0{width}d}'.format(width=2, number=i) for i in range(1, 33)]]                   

cons = pd.concat([data_p1, data_p5, data_p8, data_p9, data_p12A, data_p12B, data_p12C, data_p12D, data_p12E, data_p12F, data_p12G, data_p43], 
                 axis=1, join='inner')

# ## drop all blocks with zero-population
# cons = cons[(cons.T != 0).any()]
# shift column "GEOID10" to first position
first_column = cons.pop("GEOID10")
# insert column using insert(position,column_name,first_column) function
cons.insert(0, "GEOID10", first_column)

cons.to_csv("franklin/microdata/franklin_cons.csv", index=False)
cons

,GEOID10,P0010001,P0050003,P0050004,P0050005,P0050006,P0050007,P0050008,P0050009,P0050011,...,P043A023,P043A024,P043A025,P043A026,P043A027,P043A028,P043A029,P043A030,P043A031,P043A032
0,390490089001000,96,83,6,0,2,0,0,2,3,...,0,0,38,0,0,0,0,0,0,0
1,390490089001001,53,50,3,0,0,0,0,0,0,...,0,0,25,0,0,0,0,0,0,0
2,390490089001002,77,71,0,0,1,0,0,0,5,...,0,0,29,0,0,0,0,0,0,0
3,390490089001003,66,59,1,0,0,0,0,1,5,...,0,0,23,0,0,0,0,0,0,0
4,390490089001004,76,73,1,0,0,0,0,1,0,...,0,0,24,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22821,390490093502007,346,98,205,3,4,0,1,11,4,...,0,0,127,0,0,0,0,0,0,0
22822,390490093502008,73,46,17,0,0,1,0,7,1,...,0,0,35,0,0,0,0,0,0,0
22823,390490093502009,58,43,13,0,0,0,0,1,0,...,0,0,24,0,0,0,0,0,0,0
22824,390490093502010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22825,390490093502011,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Optimize detailed histogram

In [ ]:
# %cd "/content/gdrive/My Drive/Colab Notebooks/census_privacy"
import pandas as pd
import numpy as np
from gurobipy import Model, GRB, QuadExpr, quicksum
import torch
import csv

# define all the input data for the model
filename_cons = 'franklin/microdata/franklin_cons.csv'
cons = pd.read_csv(filename_cons)

# set up parameters
n1, n2, n3, n4, n5 = 8, 2, 2, 63, 2
N = n1 * n2 * n3 * n4 * n5         # number of attribute combinations: HHGQ (8) ∗ VOTINGAGE (2) ∗ HISPANIC (2) ∗ RACE (63) ∗ SEX (2)

with open('franklin/microdata/franklin_hist_obj.csv', 'w', newline='') as f1:
    wr1 = csv.writer(f1)
    wr1.writerow(["GEOID10", "obj"])

    with open('franklin/microdata/franklin_hist.csv', 'w', newline='') as f2:
        wr2 = csv.writer(f2)
        # set up column names
        col_names = ["GEOID10"]
        hist_names = np.empty((n1, n2, n3, n4, n5), dtype="U10")
        for k1 in range(n1):
            for k2 in range(n2):
                for k3 in range(n3):
                    for k4 in range(n4):
                        for k5 in range(n5):
                            hist_names[k1, k2, k3, k4, k5] = str(k1).zfill(2) + str(k2).zfill(2) + str(k3).zfill(2) + str(k4).zfill(2) + str(k5).zfill(2)
        col_names.extend(hist_names.flatten())
        wr2.writerow(col_names)

        for idx, row in cons.iterrows():
            GEOID10 = row["GEOID10"]

            A = torch.tensor(range(N))
            A = A.reshape([n1, n2, n3, n4, n5])

            # initialize model
            m = Model('od')
            m.Params.LogToConsole = 0

            # add objective function
            obj = QuadExpr()

            # add variables and constraints
            h = {}      ## detailed histogram (decision vairable)
            for i in range(N):
                h[i] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, ub=row["P0010001"], name="h_%d"%(i))
            m.update()

            ## P5: HISPANIC OR LATINO ORIGIN BY RACE
            q1 = cons.loc[:, cons.columns.str.startswith("P005")].to_numpy()
            res1, col_idx = {}, 0
            for x in range(n3):  # hispanic
                hist_idx_two_or_more = []
                for y in range(n4):  # race   
                    if y >= 0 and y <= 5:
                        hist_idx = torch.flatten(A[:, :, x, y, :]).tolist()
                        res1[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res1_%d"%(col_idx))
                        obj += res1[col_idx] * res1[col_idx]
                        m.addConstr(res1[col_idx] == q1[idx, col_idx] - quicksum(h[i] for i in hist_idx))
                        m.update()
                        col_idx += 1
                    else:
                        hist_idx = torch.flatten(A[:, :, x, y, :]).tolist()
                        hist_idx_two_or_more.extend(hist_idx)
                res1[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res1_%d"%(col_idx))
                obj += res1[col_idx] * res1[col_idx]
                m.addConstr(res1[col_idx] == q1[idx, col_idx] - quicksum(h[i] for i in hist_idx_two_or_more))
                m.update()
                col_idx += 1

            ## P8: RACE
            q2 = cons.loc[:, cons.columns.str.startswith("P008")].to_numpy()
            res2, col_idx = {}, 0   
            for x in range(n4):  # race
                hist_idx = torch.flatten(A[:, :, :, x, :]).tolist()
                res2[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res2_%d"%(col_idx))
                obj += res2[col_idx] * res2[col_idx]
                m.addConstr(res2[col_idx] == q2[idx, col_idx] - quicksum(h[i] for i in hist_idx))
                m.update()
                col_idx += 1

            ## P9: HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE
            q3 = cons.loc[:, cons.columns.str.startswith("P00900")].to_numpy()
            res3, col_idx = {}, 0    
            for x in range(n4):  # race
                hist_idx = torch.flatten(A[:, :, 0, x, :]).tolist()
                res3[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res3_%d"%(col_idx))
                obj += res3[col_idx] * res3[col_idx]
                m.addConstr(res3[col_idx] == q3[idx, col_idx] - quicksum(h[i] for i in hist_idx))
                m.update()
                col_idx += 1

            ## P12: SEX BY AGE BY RACE
            q4 = cons.loc[:, cons.columns.str.startswith("P012")].to_numpy()
            res4, col_idx, hist_idx_two_or_more = {}, 0, []    
            for x in range(n4):  # race
                for y in range(n5):  # sex
                    for z in range(n2):  # voting age
                        if x >= 0 and x <= 5:
                            hist_idx = torch.flatten(A[:, z, :, x, y]).tolist()
                            res4[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res4_%d"%(col_idx))
                            obj += res4[col_idx] * res4[col_idx]
                            m.addConstr(res4[col_idx] == q4[idx, col_idx] - quicksum(h[i] for i in hist_idx))
                            m.update()
                            col_idx += 1
                        else:
                            hist_idx = torch.flatten(A[:, z, :, x, y]).tolist()
                            hist_idx_two_or_more.extend(hist_idx)
            res4[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res4_%d"%(col_idx))
            obj += res4[col_idx] * res4[col_idx]
            m.addConstr(res4[col_idx] == q4[idx, col_idx] - quicksum(h[i] for i in hist_idx_two_or_more))
            m.update()

            ## P43: GROUP QUARTERS POPULATION BY SEX BY AGE BY GROUP QUARTERS TYPE
            q5 = cons.loc[:, cons.columns.str.startswith("P043")].to_numpy()
            res5, col_idx = {}, 0     
            for x in range(n5):  # sex
                for y in range(n2):  # voting age
                    for z in range(n1):  # hhgq
                        hist_idx = torch.flatten(A[z, y, :, :, x]).tolist()
                        res5[col_idx] = m.addVar(obj=0, vtype=GRB.INTEGER, lb=0, name="res5_%d"%(col_idx))
                        obj += res5[col_idx] * res5[col_idx]
                        m.addConstr(res5[col_idx] == q5[idx, col_idx] - quicksum(h[i] for i in hist_idx))
                        m.update()
                        col_idx += 1            

            m.setObjective(obj, GRB.MINIMIZE)
            m.optimize()

            # write histogram values
            hist_values = [GEOID10]
            var_values = [var.X for var in m.getVars() if 'h' == str(var.VarName[0])]
            hist_values.extend(var_values)
            wr2.writerow(hist_values)

            # write objective values
            obj = m.getObjective().getValue()
            wr1.writerow([GEOID10, obj])
            print(idx)

Evaluate histogram fit

In [76]:
import pandas as pd
import math

filename_obj = 'franklin/microdata/franklin_hist_obj.csv'
obj = pd.read_csv(filename_obj)
math.sqrt(obj["obj"].sum() / len(obj))

4.101837137798207

HHGQ (8) $*$ VOTINGAGE (2) $*$ HISPANIC (2) $*$ RACE (63) $*$ SEX (2) [from sf1 constraints]  
---------------->         
HHGQ (8) $*$ VOTINGAGE (2) $*$ HISPANIC (2) $*$ CENRACE (63)

In [26]:
import pandas as pd
import numpy as np

filename_hist = 'franklin/microdata/franklin_hist.csv'
hist = pd.read_csv(filename_hist)

col = [i[:8] for i in hist.columns]
col.remove("GEOID10")
col = np.unique(col)

for x in col:
    hist[x] = np.sum(hist.loc[:, hist.columns.str.startswith(x)].to_numpy(), axis=1)

col = np.append(["GEOID10"], col)
hist_new = hist[col]
hist_new.to_csv('franklin/microdata/franklin_hist.csv', index=False)  
hist_new

,GEOID10,00000000,00000001,00000002,00000003,00000004,00000005,00000006,00000007,00000008,...,02010153,02010154,02010155,02010156,02010157,02010158,02010159,02010160,02010161,02010162
0,390490089001000,24.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,390490089001001,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,390490089001002,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,390490089001003,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,390490089001004,19.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22821,390490093502007,15.0,57.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22822,390490093502008,5.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22823,390490093502009,7.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22824,390490093502010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22825,390490093502011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### **County-level microdata from PPMF**

In [2]:
import csv

with open("franklin/nhgis/ppmf_20210608_franklin.csv", "w", newline='') as f1:
    wr1 = csv.writer(f1)
    wr1.writerow("INTAGE,TABBLKST,TABBLKCOU,TABTRACTCE,TABBLKGRPCE,TABBLK,RTYPE,GQTYPE_PL,VOTING_AGE,CENHISP,CENRACE")
    with open("franklin/nhgis/ppmf_20210608_P.csv", "r") as f2:
        reader = csv.reader(f2)
        for row in reader:
            if row[1] == '39' and row[2] == '049':
                wr1.writerow(row)
                print(row)

In [8]:
import pandas as pd

filename_ppmf = 'franklin/nhgis/ppmf_20210608_franklin.csv'
ppmf = pd.read_csv(filename_ppmf)
ppmf['TABBLKST'] = ppmf['TABBLKST'].apply('{:0>2}'.format)
ppmf['TABBLKCOU'] = ppmf['TABBLKCOU'].apply('{:0>3}'.format)
ppmf['TABTRACTCE'] = ppmf['TABTRACTCE'].apply('{:0>6}'.format)
ppmf['TABBLK'] = ppmf['TABBLK'].apply('{:0>4}'.format)
ppmf['GEOID10'] = ppmf[['TABBLKST', 'TABBLKCOU', 'TABTRACTCE', 'TABBLK']].apply(lambda x: ''.join(x), axis=1)

ppmf.to_csv(filename_ppmf, index=False)
print(ppmf['GQTYPE_PL'].unique(), ppmf['VOTING_AGE'].unique(), ppmf['CENHISP'].unique(), ppmf['CENRACE'].unique())
ppmf

[0 7 2 5 4 1 3] [1 2] [1 2] [ 1 22  8  2  4  7  9 21 13  6 11  3  5 18 30 19 35 12 44 15 25 20 26 16
 10 14 23 48 28 38 32 42 33 37 29 24 34 27 36 45 31 47 50 43 17 46 57]

,INTAGE,TABBLKST,TABBLKCOU,TABTRACTCE,TABBLKGRPCE,TABBLK,RTYPE,GQTYPE_PL,VOTING_AGE,CENHISP,CENRACE,GEOID10
0,20210608_P,39,049,000110,1,1001,3,0,1,1,1,390490001101001
1,20210608_P,39,049,000110,1,1001,3,0,1,1,1,390490001101001
2,20210608_P,39,049,000110,1,1001,3,0,1,1,1,390490001101001
3,20210608_P,39,049,000110,1,1001,3,0,1,1,22,390490001101001
4,20210608_P,39,049,000110,1,1001,3,0,2,1,1,390490001101001
...,...,...,...,...,...,...,...,...,...,...,...,...
1163326,20210608_P,39,049,010700,1,1020,3,0,2,1,1,390490107001020
1163327,20210608_P,39,049,010700,1,1020,3,0,2,1,1,390490107001020
1163328,20210608_P,39,049,010700,1,1020,3,0,2,1,1,390490107001020
1163329,20210608_P,39,049,010700,1,1020,3,0,2,1,1,390490107001020
1163330,20210608_P,39,049,010700,1,1020,3,0,2,1,1,390490107001020

Convert to histogram: HHGQ (8) ∗ VOTINGAGE (2) ∗ HISPANIC (2) ∗ RACE (63)

In [ ]:
import pandas as pd
import numpy as np
import torch
import csv

filename_hist_new = 'franklin/microdata/franklin_hist.csv'
hist_new = pd.read_csv(filename_hist_new)

filename_ppmf = 'franklin/nhgis/ppmf_20210608_franklin.csv'
ppmf = pd.read_csv(filename_ppmf)

# set up parameters
n1, n2, n3, n4 = 8, 2, 2, 63

with open('franklin/microdata/franklin_hist_ppmf_20210608.csv', 'w', newline='') as f:
    wr = csv.writer(f)
    # set up column names
    col_names = ["GEOID10"]
    hist_names = np.empty((n1, n2, n3, n4), dtype="U10")
    for k1 in range(n1):
        for k2 in range(n2):
            for k3 in range(n3):
                for k4 in range(n4):
                        hist_names[k1, k2, k3, k4] = str(k1).zfill(2) + str(k2).zfill(2) + str(k3).zfill(2) + str(k4).zfill(2)
    col_names.extend(hist_names.flatten())
    wr.writerow(col_names)

    for idx, row in hist_new.iterrows():
        GEOID10 = row['GEOID10']
        ppmf_sub = ppmf[ppmf['GEOID10'] == GEOID10]
        hist_values = []
        for k1 in range(n1):
            for k2 in range(n2):
                for k3 in range(n3):
                    for k4 in range(n4):
                        col_value = len(ppmf_sub[(ppmf_sub['GQTYPE_PL'] == k1) & (ppmf_sub['VOTING_AGE'] == k2 + 1) & (ppmf_sub['CENHISP'] == k3 + 1) & (ppmf_sub['CENRACE'] == k4 + 1)])
                        hist_values.append(col_value)
        hist = [GEOID10]
        hist.extend(hist_values)
        wr.writerow(hist)
        print(idx)

Compare two data sets

In [4]:
import pandas as pd

filename_sf1 = 'franklin/microdata/franklin_hist.csv'
sf1 = pd.read_csv(filename_sf1)
sf1 = sf1.drop(['GEOID10'], axis=1)

filename_ppmf = 'franklin/microdata/franklin_hist_ppmf_20210608.csv'
ppmf = pd.read_csv(filename_ppmf)
ppmf = ppmf.drop(['GEOID10'], axis=1)

sf1.corrwith(ppmf, axis = 1).mean()

0.9247874178603841